### ISSUE TITLE
lighttpd ?

### ISSUE THREAD

**Issue by bestian77** [operasoftware/dns-ui#102]
Hi.

I am trying to set up this web application behind an SSL-offloader, and under lighttpd web server, and on top of that, I am using a subfolder, not root. I used the patch from issue #96 and it works fine.

-1- the links on the top row point to a non-trailing-slash URL. with HTTPS. curiously it's redirected with HTTP.
The link is https://www.example.com/mywebdns and when I click it, I'm redirected to http://www.example.com/mywebdns/. No idea where that comes from.
-2- much more annoying, web interface lists fine the zones, the templates, the users, the settings. However when I attempt to access a zone, I get a 404 in return. Am I wrong that the url-rewrite should get into https://www.example.com/mywebdns/init.php/zones/example.com ? Because that's what my lighttpd config does, but it gets a 404.

Any hint or help appreciated !

**Comment by thomas-pike** [comment]
Hi

Unfortunately I have no experience whatsoever with lighttpd, but 

1. If the SSL-offloader acts like a reverse proxy, then if possible it needs to be configured to rewrite the URLs in HTTP Location headers appropriately, much like the [ProxyPassReverse](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypassreverse) directive in Apache does.
2. Could you try using the patch from #104 and see if that works any better for you than the previous patch in #96?

**Comment by bestian77** [comment]
Hello !


I have put the changes from #104 in place. The links are all over HTTPS now, so it's fixed.
Sadly the most disturbing issue persists.
I can't edit any zone ! Every link points to an error 404. I can add a forward or a reverse zone, I can see them listed in the zones list, and in the database. But whenever I try to edit any of them, it fails. I can also add & edit SOA/NS templates or users, it's really just the zones that face the issue.

Do you have any idea how to debug this further ? Add some php debugging level, output what it gets, what it processes, to compare as to what it should get & do ?

Thanks a lot for your time !

**Comment by bestian77** [comment]
You're the man, yeah.
It works when the zone does not contain a dot !

I now figured out that something in my url rewriting was apparently not deeply tought of.
It's ok now, everything works fine.

for reference, here is it : 

  url.rewrite-final = (                                                                                                  
     "^/admin/newdns/(.*png|.*.css\\?.*|.*.js\\?.*)$" => "/admin/newdns/$1",
     "^/admin/newdns/(.*)$" => "/admin/newdns/init.php/$1"

**Comment by bestian77** [comment]
ok, testing, now....

When I try push the button for a zone deletion request or same button to abort the request, it redirects again to HTTP instead of HTTPS.

**Comment by thomas-pike** [comment]
You might have better luck with the patch in #105

**Comment by bestian77** [comment]
We're getting there... :)

Starting from new master and adding #105 i have the following issue when I press a button : 

I stick to HTTPS but it adds a second time the sub-url. I have the website hosted at : 
https://www.example.com/admin/newdns/zones/test.com
It redirects to :  
https://www.example.com/admin/newdns/admin/newdns/zones/test.com

**Comment by thomas-pike** [comment]
Interesting. Please temporarily add the following code at line 34 of `requesthandler.php`:

```
var_dump($relative_frontend_base_url); var_dump($frontend_root_url);
var_dump($relative_request_url); var_dump($absolute_request_url);
die;
```

and let me know what values you see from that. Thanks!

**Comment by bestian77** [comment]
string(13) "/admin/newdns" string(42) "https://www.example.com/admin/newdns" string(6) "/zones" string(61) "https://www.example.com/admin/newdns/admin/newdns/zones"

**Comment by bestian77** [comment]
I think we have it prefectly fine, now, I can't find any other issue anywhere ! Thank you VERY MUCH !
