### ISSUE TITLE
Updating Zones doesn't increment the serial number?

### ISSUE THREAD

**Issue by devinacosta** [operasoftware/dns-ui#103]
When I use the (dns-ui) web interface to make zone changes, it doesn't seem to be updating the serial number of the zone. Am I missing something with the config to make this happen? The Primary zone gets updated but the secondary doesn't cause the zone serial never got updated.

**Comment by devinacosta** [comment]
I found the answer:

  4 |         4 | SOA-EDIT-API | INCEPTION-INCREMENT

You need to add an entry into domainmetadata with kind = SOA-EDIT-API and content to be INCEPTION-INCREMENT.

**Comment by Napsty** [comment]
@devinacosta Can you describe this with a bit of more detail please? Are you in the database here? If yes, in which database (powerdns or dns-ui?). What's the default, what's the change?
I might have the same problem here (serial not increasing when changing in DNS-UI), but trying to understand your answer.
