### ISSUE TITLE
Serial not updating

### ISSUE THREAD

**Issue by wilix** [operasoftware/dns-ui#106]
Hi,

The demo version of DNSUI had a working feature which updates the serial number of a zone after a zone change (like a new a record).
When I install DNSUI this isn't working.

The backend is running gmysql, which supports Autoserial.
I have SOA-EDIT set by the api, see below.
```
This zone is owned by Admin
This is a Master zone
Last SOA serial number we notified: 2018111400 == 2018111400 (serial in the database)
Zone is not actively secured
Metadata items:
        SOA-EDIT        INCEPTION-INCREMENT
        SOA-EDIT-API    INCEPTION-INCREMENT
```

After a change the serial stays at 2018111400. 
How can I resolve this issue, or in which direction should this issue be fixed?

Thanks!

**Comment by thomas-pike** [comment]
The recommended zone metadata settings for DNSUI are: `SOA-EDIT-API = INCEPTION-INCREMENT` and `SOA-EDIT` should be unset (these are the settings that are used when creating new zones through DNSUI).

DNSUI does not increment the serial itself, it relies on PowerDNS to do it.

**Comment by tabakhase** [comment]
using PowerDNS 4.2 (and by the looks >=4.0) `INCEPTION-INCREMENT` is no longer a valid value for `SOA-EDIT-API` https://doc.powerdns.com/md/authoritative/upgrading/
> Incompatible change: SOA-EDIT-API now follows SOA-EDIT-DNSUPDATE instead of SOA-EDIT (incl. the fact that it now has a default value of DEFAULT).

throwing `pdns_server[346]: SOA-EDIT-API/DNSUPDATE type 'INCEPTION-INCREMENT' for zone example.com is unknown.`

[changing this](https://github.com/operasoftware/dns-ui/blob/b7f4f36e4c232db184b302c82910f375af32bfe3/model/zonedirectory.php#L102) to `DEFAULT` increments SOA as expected on dns-ui changes.

**Comment by thomas-pike** [comment]
> using PowerDNS 4.2 (and by the looks >=4.0) `INCEPTION-INCREMENT` is no longer a valid value for `SOA-EDIT-API`

Strange, this behaviour has not been seen in PowerDNS 4.0x or 4.1.

**Comment by emollusion** [comment]
> using PowerDNS 4.2 (and by the looks >=4.0) `INCEPTION-INCREMENT` is no longer a valid value for `SOA-EDIT-API` https://doc.powerdns.com/md/authoritative/upgrading/
> 
> > Incompatible change: SOA-EDIT-API now follows SOA-EDIT-DNSUPDATE instead of SOA-EDIT (incl. the fact that it now has a default value of DEFAULT).
> 
> throwing `pdns_server[346]: SOA-EDIT-API/DNSUPDATE type 'INCEPTION-INCREMENT' for zone example.com is unknown.`
> 
> [changing this](https://github.com/operasoftware/dns-ui/blob/b7f4f36e4c232db184b302c82910f375af32bfe3/model/zonedirectory.php#L102) to `DEFAULT` increments SOA as expected on dns-ui changes.

This solved my problem with new zones being created in DNSUI, ending up as INCEPTION-INCREMENT in the database domainmetadata table instead of as DEFAULT.
PowerDNS Server 4.3.2
dnsui 0.2.7
Should this be a dnsui issue?
Since it seems like dnsui is reading the setting from the PowerDNS Server configuration for default-soa-edit value and then presenting this whilst it should be presenting default, or am I missing something?
