### ISSUE TITLE
Feature Request: Option(in config.ini?) to make comment field mandatory.

### ISSUE THREAD

**Issue by tibori** [operasoftware/dns-ui#109]
We're hoping to use DNSUI in a corporate environment, where we want to have the ability to enforce the "Comment" field whenever a record is added or updated. Hope it's not too difficult to add it in as a config option.

**Comment by thomas-pike** [comment]
To be clear, are we talking about the change comment field, or the record comment field?

**Comment by tibori** [comment]
The "Update Comment" at the bottom after a change(or multiple changes) are made, but before it's submitted. Not sure how this should fit for admin/operator, but I'd be happy with it being mandatory(as an option in config.ini) for both, and then we can fine-tune later.
