### ISSUE TITLE
Feature Request: Show total number of pending changes on front page

### ISSUE THREAD

**Issue by tibori** [operasoftware/dns-ui#110]
If you have multiple zones, you have to drill down per zone to see the pending changes. It'd be nice if the total number, and the zone name that they're pending in would be shown on a tab in the main front page, so it'd be easy to locate them.

**Comment by thomas-pike** [comment]
Rather than show them all in a separate tab, the number of pending changes is shown highlighted next to each zone that has any on the zone list page.
