### ISSUE TITLE
Change "Contact" in "zone configuration" -> application crashes

### ISSUE THREAD

**Issue by christianbur** [operasoftware/dns-ui#113]
if I change the "Contact" in the "zone configuration" tab, the application crashed. Unfortunately I didn't find anything in the log. 

pdns version:  4.1.5

**Comment by christianbur** [comment]
I found the error, when clicking on "Save chanes" my browser jumps back to the old URL (used for some time), so the website is no longer accessible. Strangely enough the phenomenon does not occur with other buttons. 
But it is probably a problem of my browser and not of dnsui.
Sorry for the bug report.

**Comment by thomas-pike** [comment]
Interesting, thanks for the update. Maybe try clearing the browser cache?
