### ISSUE TITLE
DNSUI Alias Type support

### ISSUE THREAD

**Issue by devinacosta** [operasoftware/dns-ui#114]
We are trying to deploy DNSUI in AWS and convert from Route53 to PowerDNS. From what I can see PowerDNS supports ALIAS records, however the DNSUI doesn't seem to let me create records of type ALIAS?

**Comment by christianbur** [comment]
current not defined 
https://github.com/operasoftware/dns-ui/blob/68249754e7eab4944dfcd6ce9a07f6b3bc967a04/templates/zone.php#L158

do not forget the Powerdns settings.
```
resolver=[::1]:5300
expand-alias=yes
```
https://doc.powerdns.com/authoritative/guides/alias.html

**Comment by thomas-pike** [comment]
Hi

ALIAS record support was added in commit 18da549. If you use the master branch you should get that. I'll try to put out a new release soon that includes all of the latest changes.
