### ISSUE TITLE
nginx subdirectory & oauth2 authentication configuration example

### ISSUE THREAD

**Issue by captainark** [operasoftware/dns-ui#117]
Hi,

I got dns-ui working in a subdirectory on nginx.

I was also able to use [oauth2_proxy](https://github.com/pusher/oauth2_proxy) to authenticate with GitHub instead of a htpasswd file.

I forked the repo to update the wiki. My modifications are available here, if that can help someone :

https://github.com/captainark/dns-ui/wiki/Example-configuration:-nginx

**Comment by thomas-pike** [comment]
Fantastic. I'll add that to our wiki.

**Comment by thomas-pike** [comment]
Added. Thank you very much!
