### ISSUE TITLE
regex for NAPTR

### ISSUE THREAD

**Issue by joeyaben** [operasoftware/dns-ui#125]
I was not be able to add a NAPTR record within dns-ui, with the pdnsutil cli (pdnsutil add-record ZONE @ NAPTR '50 50 "s" "x-eduroam:radius.tls" "" _radsec._tcp.kennisnet.eduroam.nl') this is no issue.

After making some modifications to the data-content-pattern in the zone.php file I was be able to create the record within dns-ui.

old:
`<option value="NAPTR" data-content-pattern="[0-9]+\s+[0-9]+\s+&quot;[A-Z0-9]+&quot;\s+&quot;[\w+]+&quot;\s+&quot;[^&quot;]*&quot;\s+\S+">NAPTR</option>`

new:
`<option value="NAPTR" data-content-pattern="[0-9]+\s+[0-9]+\s+&quot;[a-zA-Z0-9]&quot;+\s+&quot;[\S+]+&quot;+\s+&quot;[\S]*&quot;+\s+[\S]+">NAPTR</option>`

I'm not sure if the new regex is causing some other issues, but for me it's working fine.

**Comment by thomas-pike** [comment]
The old regexp was trying to follow the specification of [RFC 2915](https://tools.ietf.org/html/rfc2915) but I see now that this was superseded by [RFC 3403](https://tools.ietf.org/html/rfc3403).

My proposed replacement would be: `[0-9]+\s+[0-9]+\s+"[A-Za-z0-9]+"\s*"[^"]*"\s+"[^"]*"\s+\S+`, or in HTML-escaped form: `<option value="NAPTR" data-content-pattern="[0-9]+\s+[0-9]+\s+&quot;[A-Za-z0-9]+&quot;\s*&quot;[^&quot;]*&quot;\s+&quot;[^&quot;]*&quot;\s+\S+">NAPTR</option>`
