### ISSUE TITLE
Case sensitive problem with LDAP

### ISSUE THREAD

**Issue by rmuehl** [operasoftware/dns-ui#129]
I face the following problem with LDAP auth on Linux.

1. Login to apache with user "testuser"
2. user "testuser" doesn't exist yet
3. LDAP backend does the queries, and gets back TESTUSER
4. TESTUSER is being created in the database
5. on the next request "testuser" doesn't exist 
6. backend tries to create the user again, but "TESTUSER" already exists

So the apache LDAP Auth doesn't care abaut upper or lower case, but the LDAP backend does.

**Comment by systeembeheerder** [comment]
This problem also arises with AD authentication.

**Comment by thomas-pike** [comment]
Have you tried setting the [user_case_sensitive](https://github.com/operasoftware/dns-ui/blob/master/config/config-sample.ini#L35) option to 0?

**Comment by systeembeheerder** [comment]
@thomas-pike `user_case_sensitive = 0` solved my problen. Thanx!
