### ISSUE TITLE
Browser dialog when changing records

### ISSUE THREAD

**Issue by rmuehl** [operasoftware/dns-ui#131]
Everytime I change records in a zone and klick "Save changes" a dialog box appears:

![browser-screenshot](https://user-images.githubusercontent.com/22004345/55142895-ed716f80-513d-11e9-8908-ce9bc9715bc1.png)

Is it possible to change that behavier?

**Comment by rmuehl** [comment]
I guess it's because of the unfilled (red) row you always get when hitting enter.

![inspector-screenshot](https://user-images.githubusercontent.com/22004345/55143884-f4997d00-513f-11e9-93e9-cb765482e59c.png)

**Comment by thomas-pike** [comment]
The handler is removed normally ([here](https://github.com/operasoftware/dns-ui/blob/master/public_html/extra.js#L610)). If it's not, there may be a javascript error on the page. See #127 for example.

**Comment by thomas-pike** [comment]
Closing as unreproducible.
