### ISSUE TITLE
Please cut (and tag) a new release

### ISSUE THREAD

**Issue by uedvt359** [operasoftware/dns-ui#157]
Hi! There have been quite a few changes since the last release in April 2018, and more in pull requests we (and others) have opened: 47 commits to master plus our seven pulls from udvt359 and robertpenz. 

We are aware that we have put quite a few changes out in the last few days and know that the maintainers' time is valuable, so apologies for the amount of noise generated. 

Thank you in advance!

**Comment by uedvt359** [comment]
ping @thomas-pike -- if you find time, could you please publish a new release? Last version was published in April 2018 with 62 changes since.

**Comment by thomas-pike** [comment]
Will do, now that #159 has been fixed.

**Comment by thomas-pike** [comment]
Released [v0.2.4](https://github.com/operasoftware/dns-ui/releases/tag/v0.2.4). Thank you for all of your contributions!
