### ISSUE TITLE
change SOA-EDIT-API value from INCEPTION-INCREMENT to DEFAULT

### ISSUE THREAD

**Issue by skkelma** [operasoftware/dns-ui#159]
In PowerDNS 4.2 branch support for the SOA-EDIT-API value INCEPTION-INCREMENT is dropped:
https://blog.powerdns.com/2019/08/30/powerdns-authoritative-server-4-2-0/
https://blog.powerdns.com/2018/12/07/important-changes-in-powerdns-authoritative-server-4-2-0/
So it would be nice to change the fixed SOA-EDIT-API value to "DEFAULT" in model/zone.php (627) and model/zonedirectory.php (102).
From my understanding this works like the wanted autoserial behaviour.
https://doc.powerdns.com/authoritative/domainmetadata.html#soa-edit-api
https://doc.powerdns.com/authoritative/dnsupdate.html#soa-edit-dnsupdate-settings

**Comment by mikej-hc** [comment]
This query worked for me to bulk update the field.
`UPDATE domainmetadata SET content='DEFAULT' WHERE kind='SOA-EDIT-API' AND content='INCEPTION-INCREMENT';`
