### ISSUE TITLE
error on deleting zone

### ISSUE THREAD

**Issue by skkelma** [operasoftware/dns-ui#160]
when deleting a zone, after pressing the final "DELETE" button, an error is generated:
`Oops! Something went wrong!`
this is confusing, since the zone was in fact deleted!
error log:
Pest_NotFound: {"error": "Not Found"} in /var/www/dnsui/Pest.php:311, referer: http://dns-ui-server/zones/example.com
Stack trace:, referer: http://dns-ui-server/zones/example.com
#0 /var/www/dnsui/Pest.php(268): Pest->checkLastResponseForError(), referer: http://dns-ui-server/zones/example.com
#1 /var/www/dnsui/Pest.php(154): Pest->doRequest(Resource id #2), referer: http://dns-ui-server/zones/example.com
#2 /var/www/dnsui/powerdns.php(30): Pest->get('zones/example.com.', Array, Array), referer: http://dns-ui-server/zones/example.com
#3 /var/www/dnsui/model/zone.php(224): PowerDNS->get('zones/example.com.'), referer: http://dns-ui-server/zones/example.com
#4 /var/www/dnsui/views/zone.php(32): Zone->list_resource_record_sets(), referer: http://dns-ui-server/zones/example.com
#5 /var/www/dnsui/requesthandler.php(63): require('/var/www/dnsui/...'), referer: http://dns-ui-server/zones/example.com
#6 /var/www/dnsui/public_html/init.php(18): require('/var/www/dnsui/...'), referer: http://dns-ui-server/zones/example.com
#7 {main}, referer: http://dns-ui-server/zones/example.com
access log:
"POST /zones/example.com HTTP/1.1" 303 268 "http://dns-ui-server/zones/example.com" 
"GET /zones/example.com HTTP/1.1" 500 2752 "http://dns-ui-server/zones/example.com"
maybe the last GET on the deleted zone triggers the error (HTTP code 500)?

**Comment by rmuehl** [comment]
Same here since pdns update from 4.1 to 4.3.
