### ISSUE TITLE
Add LUA record type

### ISSUE THREAD

**Issue by joeyaben** [operasoftware/dns-ui#168]
Is it possible to add support for the LUA-records which have been available since PowerDNS Authoritative Server version 4.2 and later.

[https://doc.powerdns.com/authoritative/lua-records/](https://doc.powerdns.com/authoritative/lua-records/)

Currently I have to create them by mysql cli, do this within dns-ui would be awesome.

**Comment by maltris** [comment]
I added this in this pull request https://github.com/operasoftware/dns-ui/pull/200 and recently changed the ordering as requested. It adds the menu option for the LUA-type.
