### ISSUE TITLE
Too long Changelog for zone.

### ISSUE THREAD

**Issue by sipopo** [operasoftware/dns-ui#179]
Hi, your work is realy great thank you.

We have zone for monitoring and using DNSUI api for make changes in it.
So, we have already more than 30000 changes and web is very slow because of that.

Can we limit the number of showing changes if we whant to see only records or can we separate changelog to diffenet scope?

**Comment by uedvt359** [comment]
We're starting to hit those limitations as well, so I'm trying to find a way to filter (or better, search in) changelogs.

I had a look in the [table schemas](https://github.com/operasoftware/dns-ui/blob/master/migrations/002.php#L13-L35). The `changeset` table stores a record for each changelog entry; each
changelog is then made up of one or more rows from the `change` table. However, the juicy details are stored there as serialized PHP objects, so they can't be searched through.

The (useful) information available in `changeset` is just `author_id`, `change_date` and `comment`. This leaves us with the following options:

- paginate results
- search through comment
- limit to date range
- filter by author (least useful, IMO)

I'd like to implement one or more of the above; @thomas-pike, what would be your preference here?

**Comment by thomas-pike** [comment]
I think that primarily, to solve the problem of page load becoming slow, the most important thing is to implement pagination. Search and date range options definitely would be nice to have though. Any contributions you are able to make will be gratefully accepted.

Apologies for the use of serialized PHP objects, that could definitely have been done better.

**Comment by uedvt359** [comment]
Here's the pull request: https://github.com/operasoftware/dns-ui/pull/190
