### ISSUE TITLE
Public zone warning even though the zone is private

### ISSUE THREAD

**Issue by fnordpojk** [operasoftware/dns-ui#18]
This may be by design and I'm just misunderstanding, but when adding records to a zone classified private, I still get this warning:

"Warning: x.x.x.x is a local IP address. Adding it to a public zone does not make it accessible externally. Only proceed if you know what you are doing."

I'd think I'd only get that warning if my zone was classified public?

**Comment by thomasp-opera** [comment]
Ah, the "Zone classification" field isn't actually what is used to trigger this warning (that field is just added as a way to allow you to classify zones in any arbitrary way - and we actually use it to determine which zones to sync to our public servers).

The warning you are seeing here is triggered based on the value provided in the `local_zone_suffixes` setting in `config/config.ini`, and local IP addresses are detected based on the values of `local_ipv4_ranges` and `local_ipv6_ranges` (you could disable the warnings completely by emptying the range fields in the config file as they are not used for anything else).

There is almost certainly room for improvement here.

**Comment by thomasp-opera** [comment]
To clarify a bit more, if you add `foobar.example.com` to `local_zone_suffixes` then you will not receive these warnings for that domain or any subdomains of it.

**Comment by fnordpojk** [comment]
As I thought, I had misunderstood the feature. :)

Thank you for clarifying!
