### ISSUE TITLE
ErrorException: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in core.php:160

### ISSUE THREAD

**Issue by zerwes** [operasoftware/dns-ui#205]
IMHO php 8.2 related

**Comment by zerwes** [comment]
for the impatient: a hotfix release can be found at https://github.com/Rosa-Luxemburgstiftung-Berlin/dns-ui/releases/tag/v0.2.7-203-206

**Comment by thomas-pike** [comment]
Fixed in b17fdbaa.
