### ISSUE TITLE
Add support for PTR records in forward zones

### ISSUE THREAD

**Issue by SPodjasek** [operasoftware/dns-ui#22]
It's a common case when you manage only part of C-class to have this kind of records in forward zone.

And as I've just verified there's no support for CNAME RR's in reverse zones - same use case scenario.

**Comment by thomasp-opera** [comment]
I've never heard of the use of PTR records in forward zones before and could not find anything relevant via Google. Can you show me some examples of this usage?

Regardless, it should be trivial for us to add support for both PTR records in forward zones and CNAME records in reverse zones.

**Comment by SPodjasek** [comment]
It's described in RFC2317, more specifically here: https://tools.ietf.org/html/rfc2317#section-5.2

**Comment by thomasp-opera** [comment]
Perfect, thank you for the explanation. Support added.

**Comment by SPodjasek** [comment]
That's what I call lightning fast issue resolution :smile: Thnx
