### ISSUE TITLE
New zone replication type always set to Master, even when Native chosen

### ISSUE THREAD

**Issue by pasikarkkainen** [operasoftware/dns-ui#30]
I've configured the default replication type to be "Native" in the dns-ui settings.
Then I create/add a new zone from the web interface, and make sure "Native" is chosen as the replication type. I also used browser developer tools and made sure the POST request shows kind as "Native". So all should be fine..

But after the zone is added the Replication type is "Master", not "Native".

It seems there's a bug..

**Comment by thomasp-opera** [comment]
Confirmed, though the actual behaviour is that it creates the zone correctly in PowerDNS but fails to set the correct value in the local database. Workaround: view the zone list after creating the zone and it will refresh the correct data from PowerDNS.

Should be an easy fix though.
