### ISSUE TITLE
dns-ui has a route for users but users.php file is missing

### ISSUE THREAD

**Issue by pasikarkkainen** [operasoftware/dns-ui#31]
It seems dns-ui routes.php has the following:
        '/users' => 'users',

But that doesn't work.. going to /users URL results in the following in error.log:

[Fri Nov 17 20:32:18.418460 2017] [:error] [pid 138] [client 192.168.1.101:39636] 1510943538: Exception: View file /opt/dns-ui/views/users.php missing. in /opt/dns-ui/requesthandler.php:66
[Fri Nov 17 20:32:18.418500 2017] [:error] [pid 138] [client 192.168.1.101:39636] 1510943538: Stack trace:
[Fri Nov 17 20:32:18.418504 2017] [:error] [pid 138] [client 192.168.1.101:39636] 1510943538: #0 /opt/dns-ui/public_html/init.php(18): require()
[Fri Nov 17 20:32:18.418508 2017] [:error] [pid 138] [client 192.168.1.101:39636] 1510943538: #1 {main}

**Comment by thomasp-opera** [comment]
Indeed, the existence of this route is a bug, but fortunately the first implementation of the `/users` page is coming soon.
