### ISSUE TITLE
Deleting a zone

### ISSUE THREAD

**Issue by semaja2** [operasoftware/dns-ui#33]
Not sure if I am missing the option, but it appears there is no ability in the interface to delete a zone?

If it is missing it would be great to add it, possibly with some specific permissions (eg. group to add a zone, group to delete a zone etc)

**Comment by thomasp-opera** [comment]
Currently this is not implemented. I think that if we are to implement it we will need to provide some safeguards against accidental/malicious zone deletion.

Also, if using master/slave replication, we need to make it clear to the user that the zone will not be automatically deleted from the slave servers (as this is not possible to do).
