### ISSUE TITLE
Option to allow creation of PTR record when creating A or AAAA record

### ISSUE THREAD

**Issue by Learloj** [operasoftware/dns-ui#37]
If I understand the functional workings and code correct, every time a record is added, a check is performed if a reverse zone exists, and if it does and doesn't have a reverse record already, it will create one.

If this is indeed the workings, then I think it'd be nice if this was configurable. That way you can choose if you want to have the system automatically create reverse DNS records for you or not.

**Comment by thomasp-opera** [comment]
Agreed, this should probably be an option. Whether it should be an option that users can select every time they save changes, or whether it should be a global setting (or a combination of the two) I'm not sure.

**Comment by Learloj** [comment]
Personally I'd prefer the 2nd option.

**Comment by thomasp-opera** [comment]
That is absolutely fine.

**Comment by atj** [comment]
Implemented in PR #47.

**Comment by thomasp-opera** [comment]
Resolved in #47. Thank you for your contribution!
