### ISSUE TITLE
Feature request: Allow change requests from admins

### ISSUE THREAD

**Issue by TiagoTT** [operasoftware/dns-ui#49]
Thanks for this nice PowerDNS frontend.

Our team would like to use this nice project with a peer-review work flow where all users could submit changes for review, including global and zone admins. Admins would still be allowed to save changes immediately or maybe a configuration flag could configure the behavior.

I have identified some bits of code that would need change, but I am unsure if these changes would be enough or they might bring problems.

```
diff --git a/templates/zone.php b/templates/zone.php
index 5105c74..d40fb8e 100644
--- a/templates/zone.php
+++ b/templates/zone.php
@@ -203,6 +203,7 @@ global $output_formatter;
                                <div id="errors"></div>
                                <?php if($active_user->admin || $active_user->access_to($zone) == 'administrator') { ?>
                                <p><button type="submit" id="zonesubmit" name="update_rrs" value="save" class="btn btn-primary">Save changes</button></p>
+                               <p><button type="submit" id="zonesubmit" name="update_rrs" value="request" class="btn btn-primary">Request changes</button></p>
                                <?php } else { ?>
                                <p><button type="submit" id="zonesubmit" name="update_rrs" value="request" class="btn btn-primary">Request changes</button></p>
                                <?php } ?>
diff --git a/views/zone.php b/views/zone.php
index dcd7c2c..284db9c 100644
--- a/views/zone.php
+++ b/views/zone.php
@@ -69,7 +69,7 @@ if($_SERVER['REQUEST_METHOD'] == 'POST') {
                foreach($_POST['updates'] as $update) {
                        $json->actions[] = json_decode($update);
                }
-               if($active_user->admin || $active_user->access_to($zone) == 'administrator') {
+               if($_POST['update_rrs'] == 'save' && ($active_user->admin || $active_user->access_to($zone) == 'administrator')) {
                        try {
                                $zone->process_bulk_json_rrset_update(json_encode($json));
                                redirect();
```

I did not setup a test environment yet but if other people are interested in this feature, I could test and submit a PR.

**Comment by thomasp-opera** [comment]
An interesting idea, and one that should be quite easy to implement (probably not much more needed than the changes you listed). I think it might be a little confusing though if the functionality is not explained to the user in some way ("why are there 2 buttons, which one do I click?"). It would be interesting to hear from others:

1. If they think it could be a useful feature to them.
2. If they would want a configuration option for disabling this.
3. If they would want a configuration option for enforcing all changes to go through review.

My personal opinion is that as long as we make it self-explanatory enough to the end-user then there's probably no reason for (2). It may be that we just need to change the text on the buttons slightly. eg. "Request changes" -> "Request review of changes".

As for (3), I have no strong opinion on this.

**Comment by TiagoTT** [comment]
Thanks for you quick reply.
I agree that "Request review of changes" would be a better label for the button.
As for having options to disable or force change review, I have no strong opinion, but option 3 seemed reasonable as you could retain current behavior as default and avoid confusing existing users.

**Comment by TiagoTT** [comment]
I have submitted a PR for evaluation that implements option 3.
This should allow others to test the proposed changes.
It was successfully tested on a local installation.

**Comment by TiagoTT** [comment]
Thanks @thomasp-opera
