### ISSUE TITLE
How do I put it behind an Haproxy?

### ISSUE THREAD

**Issue by 3g0** [operasoftware/dns-ui#50]
I've configured my haproxy to deal with https stuff and forward the "/pdns" requests to an apache virtualhost. 
If I request https//mysite.com/pdns I got redirected to 
https//mysite.com/zones
not 
https//mysite.com/pdns/zones 
even if in my config file I put
baseurl = https://mysite.com/pdns

Thanks a lot

**Comment by thomasp-opera** [comment]
Changing the path in the base URL is currently not supported I'm afraid. It will require a lot of changes in the templates to use the specified path where currently it is hardcoded to `/`. It is probably worth doing though.
