### ISSUE TITLE
New zones lack SOA_EDIT definition?

### ISSUE THREAD

**Issue by TiagoTT** [operasoftware/dns-ui#55]
We have found that the SOA serial number on PowerDNS database does not match the SOA serial number on the DNS replies on the PowerDNS master.

For example we see `Serial number 2018030901` on dns-ui zone configuration, which matches the value on the MySQL backend database of the PowerDNS master. And PowerDNS master reply to the DNS request of the SOA record contains a serial like `1520616586`, which keeps changing all the time because we had `default-soa-edit=EPOCH` on the PowerDNS master configuration.

I recognize that `default-soa-edit=EPOCH` is deprecated and it is our problem, but I wonder if dns-ui should perhaps explicitly define the `SOA_EDIT` of the zone just like it defines `SOA_EDIT_API` on zone create and restore operations.

I have tested the code change to define SOA_EDIT to the same value as SOA_EDIT_API, and it showed almost the expected behavior. The only odd thing now is that, on SOA records in DNS replies, PowerDNS will add 2 units to the serial on the database (which is seen via the API in dns-ui). And the extra odd thing is that after about 200 updates it stops adding these 2 units, but this is PowerDNS problem/feature for sure.

**Comment by TiagoTT** [comment]
Although usually I prefer explicit settings, maybe adding a note on the installation instructions about the required `default-soa-edit=INCEPTION-INCREMENT` setting in PowerDNS master configuration file would be enough to avoid replication issues.

**Comment by thomasp-opera** [comment]
We do not use `default-soa-edit` at all - we have it at its default (ie. empty), which works for us as we never make any edits directly in the PowerDNS database. I seem to recall that we also saw some weird issues when we had both `SOA_EDIT` and `SOA_EDIT_API` set to `INCEPTION-INCREMENT`, though right now I don't remember what those issues were.

I think that further digging is required before changing the current behaviour. Perhaps the values for both `SOA_EDIT` and `SOA_EDIT_API` should be changed into configuration options so that server owners can decide for themselves.

**Comment by TiagoTT** [comment]
I understand your point, we will test without any `default-soa-edit` value in PowerDNS master configuration file.
A configuration option for each `SOA_EDIT` and `SOA_EDIT_API` might be nice and the current behavior could be preserved by the default values.

**Comment by TiagoTT** [comment]
I have successfully tested replication without any `default-soa-edit` value in PowerDNS master configuration file. And the SOA serial number is not incremented by 2 on the DNS replies from the master. It seems this issues was just caused by me trying to fix my problem the wrong way.
So indeed it not only unnecessary to define SOA_EDIT for the zones but it was actually a bad idea as it is the source of the strange behavior (serial +2 on DNS replies).
Thanks for your help @thomas-pike !
