### ISSUE TITLE
Alternative to LDAP?

### ISSUE THREAD

**Issue by TiagoTT** [operasoftware/dns-ui#60]
While we had plans to use LDAP initially, we are also looking at an alternative way to pass user data (name, email and groups) into the PHP application.
As we already use Google Oauth to authenticate users, we considered using Google Directory as an alternative to LDAP.

While trying to keep this new feature generic and not dependent on Google Oauth or Google Directory, I imagined that the webserver would be responsible to get all user data and pass it via PHP variables, just like the `PHP_AUTH_USER` variable is passed already. This should be compatible with any Single-Sign-On system that can get the required user data into variables.

I have a working prototype code that is not very polished yet: https://github.com/BrandwatchLtd/dns-ui/commit/26e9e4f46f7dcc337269a86bcb39d8ed4076c999
In case this is an interesting feature, I can open a PR. What do you think?

**Comment by thomas-pike** [comment]
I've taken a look at the code and I like what I see; definitely worthy of a PR. I'm interested to hear how well the setup works for you.

**Comment by TiagoTT** [comment]
Ok, PR is here: https://github.com/operasoftware/dns-ui/pull/61
I am still cleaning up the code but this is how it looks now on the Lua side: https://github.com/BrandwatchLtd/nginx-google-oauth/tree/user_profile

**Comment by TiagoTT** [comment]
For reference, this is the PR opened on nginx-google-oauth to implement the retrieval of Google Directory Groups membership list of a the authenticated user.
https://github.com/cloudflare/nginx-google-oauth/pull/33

**Comment by TiagoTT** [comment]
Thanks for reviewing and merging @thomas-pike , I am now closing this issue.
For reference, the suggested change was merged in https://github.com/operasoftware/dns-ui/commit/aefe72466ac3ca8ce772d458b487179d5e1977c0 .
