### ISSUE TITLE
Installed, but can't figure out how to get Admin access.

### ISSUE THREAD

**Issue by devinacosta** [operasoftware/dns-ui#65]
I have everything installed, Apache is talking to LDAP, when I look into the Postgres database I see that there are domains listed in zone table. However I can't figure out how to add users so we can manage the domains. As far as I know everything is correct in regards to the LDAP User/Group config.ini, and i have manually run the 'ldap_update.php' but still nothing?

Suggestions?

dnsui=> select * from user;
 current_user
--------------
 dnsui-user
(1 row)

dnsui=> select * from zone;
 id |   pdns_id   |    name     |   serial   | active | account |  kind  | dnssec
----+-------------+-------------+------------+--------+---------+--------+--------
  1 | lnx.ninja.  | lnx.ninja.  | 2018040202 | t      |         | Native |      0
  2 | domain.com. | domain.com. | 2018041100 | t      |         | Master |      0
(2 rows)

**Comment by thomas-pike** [comment]
Hard to say for sure, but it would seem like it has to be something wrong with the LDAP configuration in `config.ini`. To investigate further, try running `select * from "user";` (note the surrounding quotes - they are needed in this case) to see what's actually in the `user` table.

**Comment by devinacosta** [comment]
It appears I was able to update the table and give myself admin privileges. appears i'm good to go right now.
