### ISSUE TITLE
DNSSEC side effects (no rectify)

### ISSUE THREAD

**Issue by bionicman** [operasoftware/dns-ui#69]
Hello.

It's not so much about DNS-UI, but about PDNS (v4.1).

I have secured zone from UI, next extracted DS from `pdnsutil show-zone` and handed to the registrar.

But I got these effect: https://community.cloudflare.com/t/1-1-1-1-cant-resolve-m-geektimes-com/17264. Because it need to exec `pdnsutil rectify-zone` after securing zone. If this is not done, all NSEC records will be:
```
...
example.com <ttl> IN NSEC example.com ...
...
```

After the rectify-zone it's becomes normal (recursive all zone records):
```
...
example.com <ttl> IN NSEC <next>.example.com ...
...
```

Perhaps it would be correct to perform API-method for zone rectifing after any manipulation with it. I dont know about automatic rectifing zone after any changes. This can be solved with the API-RECTIFY in domainmetadata but this is not enabled by default for any created zone.

**Comment by thomas-pike** [comment]
Hi

Yes, I believe the best solution is for us to do some or all of the following:
* Provide UI for viewing/modifying the domain metadata.
* Default to enabling API-RECTIFY when turning on DNSSEC for a zone.
* Provide a warning if DNSSEC is enabled and API-RECTIFY is not enabled.
