### ISSUE TITLE
autocreate_reverse_records doesn't seem to do anything

### ISSUE THREAD

**Issue by vectr0n** [operasoftware/dns-ui#87]
I have noticed that even when this option is set to 0 in the config it still attempts to auto create reverse records, it has been a huge headache for us. I would imagine this is a bug and not the intended behaviour to ignore the config options. Everything else works as expected, keep up the good work!

**Comment by CyBeRoni** [comment]
https://github.com/operasoftware/dns-ui/pull/82

**Comment by thomas-pike** [comment]
Resolved in #82. Thank you @CyBeRoni!
