### ISSUE TITLE
Example of json API call

### ISSUE THREAD

**Issue by Koma-Andrea** [operasoftware/dns-ui#88]
Hi, just wondering if anyone could create some example for the API calls.
I could not find any example anywere and to me the code is not self explanatory.

Thank you

**Comment by thomas-pike** [comment]
Hi, there is API documentation that you can see by visiting the URL `/api/v2` in your installation (eg. https://dnsui.xiven.com/api/v2). Hopefully that's what you're looking for?

**Comment by koma85** [comment]
Absolutely, just come back because digging around (in the view directory) I've found the api.php page and the api/v2 hint. 

Maybe you could add a link in the README.md ? I assure you that is pretty obscure to find to a non programmer.

Thank you very much!

**Comment by thomas-pike** [comment]
> Maybe you could add a link in the README.md ? I assure you that is pretty obscure to find to a non programmer.

Yes, good idea.
