### ISSUE TITLE
multiple record ADD lost because of one error

### ISSUE THREAD

**Issue by nb71** [operasoftware/dns-ui#9]
When adding multiple records, if one is in wrong format, al update fails an all input lost.

EX:  Record a.pipo.com./CNAME 'pepe.com': Not in expected format (parsed as 'pepe.com.')

**Comment by thomasp-opera** [comment]
Indeed. I would actually consider this 2 issues. Firstly that this system needs to make the input of CNAME and other similar record types easier and more fault-tolerant, and secondly what you reported - that data is lost if the submit fails.

The first part I am actually already working on.

**Comment by thomasp-opera** [comment]
Both parts of this issue are addressed in #10
