### ISSUE TITLE
Something went wrong  - user created but can't view zones

### ISSUE THREAD

**Issue by billjamzz** [operasoftware/dns-ui#95]
I can see in logs that ldap login is accepted and it created a user:
[Thu Sep 13 14:21:49.365300 2018] [:error] [pid 10479] [client 10.4.9.233:51256] 1536873709: UserAlreadyExistsException: A user already exists with uid Bill.James in /var/www/dnsui_prod/model/userdirectory.php:54, referer: https://prod.billj7-6.test.j2noc.com/zones
...
[Thu Sep 13 14:44:26.513216 2018] [:error] [pid 10484] [client 10.4.9.233:52134] 1536875066: #1 /var/www/dnsui_prod/requesthandler.php(24): UserDirectory->get_user_by_uid('bill.james'), referer: https://prod.billj7-6.test.j2noc.com/zones
[Thu Sep 13 14:44:26.513218 2018] [:error] [pid 10484] [client 10.4.9.233:52134] 1536875066: #2 /var/www/dnsui_prod/public_html/init.php(18): require('/var/www/dnsui_...'), referer: https://prod.billj7-6.test.j2noc.com/zones
[Thu Sep 13 14:44:26.513220 2018] [:error] [pid 10484] [client 10.4.9.233:52134] 1536875066: #3 {main}, referer: https://prod.billj7-6.test.j2noc.com/zones

dnsui_proddb=# SELECT * FROM "user";
 id |    uid     |    name    |       email       | auth_realm | active | admin | developer | csrf_token 
----+------------+------------+-------------------+------------+--------+-------+-----------+------------
  1 | Bill.James | Bill James | Bill.James@j2.com | LDAP       |      1 |     1 |         0 | 

but I notice no csrf_token.
I'm not sure how to troubleshoot php code.
I'm running the latest git version on centos7.5. Unfortunately the error output is not very useful.
I just know its getting a 500 error on / or /zones.
How do I troubleshoot what is causing error?
I can run api commands fine against pdns master.

Is there a debug option that causes 'error_details' to get filled in?
I do have LogLevel debug set.

**Comment by thomas-pike** [comment]
This _looks_ like a bug related to case-sensitivity of the username. I say this because of the difference between the function call in the exception (`->get_user_by_uid('bill.james')`) compared to what you have in the database (`Bill.James`), and the fact that it appears to be trying to insert a new user record.

To confirm whether or not this is the case, try logging in with the username exactly as it is in the database.

**Comment by billjamzz** [comment]
ah, yes! it get's further now. We had seen that before and use this to fix postgres:
psql  -c 'CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public; ALTER TABLE public."user" ALTER COLUMN uid TYPE citext  COLLATE pg_catalog."default";'  database_name

now on to my next error...:
PHP Fatal error:  Uncaught ErrorException: htmlspecialchars() expects parameter 1 to be string, object given in /var/www/dnsui_prod/core.php:114\nStack trace:\n#0 [internal function]: exception_error_handler(2, 'htmlspecialchar...', '/var/www/dnsui_...', 114, Array)\n#1 /var/www/dnsui_prod/core.php(114): htmlspecialchars(Object(User))\n#2 /var/www/dnsui_prod/templates/error500.php(55): out(Object(User))\n#3 /var/www/dnsui_prod/pagesection.php(69): include('/var/www/dnsui_...')\n#4 /var/www/dnsui_prod/pagesection.php(57): PageSection->generate()\n#5 /var/www/dnsui_prod/templates/base.php(74): PageSection->get('content')\n#6 /var/www/dnsui_prod/pagesection.php(69): include('/var/www/dnsui_...')\n#7 /var/www/dnsui_prod/views/error500.php(32): PageSection->generate()\n#8 /var/www/dnsui_prod/requesthandler.php(82): require('/var/www/dnsui_...')\n#9 [internal function]: exception_handler(Object(Error))\n#10 {main}\n  thrown in /var/www/dnsui_prod/core.php on line 114

fun times. At least other links work, Templates, Users, Settings, just not Zones.

btw, I added this line to end of templates/error500.php and at least it display the error.
But doesn't make it any easier to understand.

<p> error number: <?php out($this->get('error_number')) ?>, error_details:  <?php out($this->get('error_details')) ?>, user: <?php out($this->get('active_user')) ?> </p>

**Comment by thomas-pike** [comment]
The stack trace above is actually related to the code you have added: you're trying to output the active user, which is an object, not a string.

If you (temporarily) want the application to display more useful error messages prior to the login step, you can do this a little more easily by commenting out the following line numbers in `views/error500.php`: 20, 21, 24 & 25. You shouldn't leave this permanently like this though, since it allows all users to view the details of the stack traces.

**Comment by billjamzz** [comment]
when I take that code out I just get the "oops" page. No error in ssl_error_log or anywhere else I've seen.  I know zones are fine, because I have another dnsui server that can read them fine.

**Comment by thomas-pike** [comment]
Did you try commenting out the lines I suggested? (In `views/error500.php`, _not_ `templates/error500.php`)

**Comment by thomas-pike** [comment]
If you're logged in successfully though, you shouldn't need to do that. You can update your user entry in the database to have `developer` = `1` and it will show full errors to you in the UI.

**Comment by billjamzz** [comment]
yes, commented out lines 20-25 in views, still no error info displayed.
I also tried setting my user developer = 1; no error detail, just "oops".

**Comment by thomas-pike** [comment]
Don't comment out lines 22 and 23 :)

**Comment by billjamzz** [comment]
oops.  :-)
that's much more helpful.


Function | Arguments | Location
-- | -- | --
punycode_to_utf8 | am-i-pdns-corp. | /var/www/dnsui_corp/templates/zones.php line 68
include | /var/www/dnsui_corp/templates/zones.php | /var/www/dnsui_corp/pagesection.php line 69
generate |   | /var/www/dnsui_corp/pagesection.php line 57
get | content | /var/www/dnsui_corp/templates/base.php line 74
include | /var/www/dnsui_corp/templates/base.php | /var/www/dnsui_corp/pagesection.php line 69
generate |   | /var/www/dnsui_corp/views/zones.php line 79
require | /var/www/dnsui_corp/views/zones.php | /var/www/dnsui_corp/requesthandler.php line 64
require | /var/www/dnsui_corp/requesthandler.php | /var/www/dnsui_corp/public_html/init.php line 18

**Comment by billjamzz** [comment]
i left out the error part:
Error "Call to undefined function idn_to_utf8()"

Occurred in /var/www/dnsui_corp/core.php line 459

**Comment by billjamzz** [comment]
oh, is that because my encoding is wrong?
     Name     |   Owner    | Encoding  | Collate | Ctype |   Access privileges   
--------------+------------+-----------+---------+-------+-----------------------
 dnsui_corpdb | dnsui-user | **SQL_ASCII** | C       | C     | 

guess I need to look into how to change that....

**Comment by thomas-pike** [comment]
Actually, I'd say it's because you don't have the PHP-intl module installed. [idn_to_utf8](http://php.net/manual/en/function.idn-to-utf8.php) is a function provided by that module.

**Comment by billjamzz** [comment]
ah ha, it works now!
Thank you VERY much for your help!!
I like dns-ui very much, just having problems duplicating the install process.
