### ISSUE TITLE
dns-ul in subdirectory not working?

### ISSUE THREAD

**Issue by LoremoCH** [operasoftware/dns-ui#98]
I installed dns-ui on Debian Stretch in a sub-directory of an existing virtual host and adjusted the baseurl inside config.ini:
`baseurl = https://mydomain.tld/dnsui`

Unfortunately this does not work. The menu bar looks normal, below I always get:
```
Page not found
Sorry, but the address you've given doesn't seem to point to a valid page.
```

My apache config:
```
Alias /dnsui /opt/dnsui/public_html

<Directory /opt/dnsui/public_html>
        DirectoryIndex init.php
        FallbackResource /dnsui/init.php
</Directory>
```

The AllowEncodedSlashes NoDecode config is inside the virtual host config.

For me that looks like the router somehow can't find the views or ignores the baseurl parameter. If i click on the Opera logo, the browser goes to https://mydomain.tld/ and not https://mydomain.tld/dnsui.

**Comment by LoremoCH** [comment]
On my attempt to solve the problem I found Pull Request #96 from @jsoref which solves the issue.

The problem with the link on the Opera logo remains.

**Comment by jsoref** [comment]
I didn't really worry about the logo going to the wrong place, since it was customizable and I put something else there, but yes, I did consider that the link was probably doing the wrong thing... Fixing that should be doable...

**Comment by jsoref** [comment]
The additional commit above fixes that problem :-)

**Comment by thomas-pike** [comment]
@jsoref @LoremoCH Could you please try the patch in #104?
